ilib/config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  get 'books/new' => 'books#new', as: :new_book
  get 'books/:id' => 'books#show', as: :book
  post 'books' => 'books#create'
  get 'books/:id/edit' => 'books#edit', as: :edit_book
  patch 'books/:id' => 'books#update'
delete 'books/:id' => 'books#delete'

get 'authors/new' => 'authors#new', as: :new_author
get 'authors/:id' => 'authors#show', as: :author
post 'authors' => 'authors#create'
get 'authors/:id/edit' => 'authors#edit', as: :edit_author
patch 'authors/:id' => 'authors#update'
delete 'authors/:id' => 'authors#delete'
end

ilib/app/models/author.rb
class Author < ActiveRecord::Base
end

ilib/app/models/book.rb
class Book < ActiveRecord::Base
end

ilib/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ilib/app/controllers/author_controller.rb
class AuthorController < ApplicationController
  def create
    @author = author.new
    @author.name = params[:name][:name]
    @author.bio = params[:bio][:bio]
    @author.photo_url = params[:photo_url][:photo_url]
    if @author.save
      redirect_to root_path
    else
      render :new
    end
  end

  def new
    @author = Author.new
  end

  def show
    @author = Author.find_by id: params[:id]
  end

  def update
    @author.name = params[:name][:name]
    @author.bio = params[:bio][:bio]
    @author.photo_url = params[:photo_url][:photo_url]

    if @author.save
      redirect_to edit_author_path
    else
      render :edit
    end
  end

  def edit
      @author = Author.find_by id: params[:id]
  end

  def delete
    @author = Author.find_by id: params[:id]
      @author.destroy
      redirect_to root_path
     end
  end

  def destroy
    @author = Author.find_by id: params[:id]
      @author.destroy
      redirect_to root_path
     end

  def index
    @authors = Author.all.order("title asc")
  end
end

ilib/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all.order("title asc")
  end

  def show
    @book = Book.find_by id: params[:id]
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new
    @book.title = params[:book][:title]
    @book.photo_url = params[:book][:photo_url]
    @book.price = params[:book][:price]

    if @book.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @book = Book.find_by id: params[:id]
  end

  def update
      @book = Book.find_by id: params[:id]
      @book.title = params[:book][:title]
      @book.photo_url = params[:book][:photo_url]
      @book.price = params[:book][:price]

      if @book.save
        redirect_to edit_book_path
      else
        render :edit
      end
  end

  def destroy
    @book = Book.find_by id: params[:id]
    @book.destroy
    redirect_to root_path
  end

  def delete
    @book = Book.find_by id: params[:id]
      @book.destroy
      redirect_to root_path
     end
end

ilib/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

ilib/app/helpers/application_helper.rb
module ApplicationHelper
end

ilib/app/helpers/author_helper.rb
module AuthorHelper
end

ilib/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ilib/app/views/author/create.html.erb
<h1>Author#create</h1>
<p>Find me in app/views/author/create.html.erb</p>

ilib/app/views/author/delete.html.erb
<h1>Author#delete</h1>
<p>Find me in app/views/author/delete.html.erb</p>

ilib/app/views/author/destroy.html.erb
<h1>Author#destroy</h1>
<p>Find me in app/views/author/destroy.html.erb</p>

ilib/app/views/author/edit.html.erb
<h1>Author#edit</h1>
<p>Find me in app/views/author/edit.html.erb</p>

ilib/app/views/author/index.html.erb
<h1>Author#index</h1>
<p>Find me in app/views/author/index.html.erb</p>

ilib/app/views/author/new.html.erb
<h1>Author#new</h1>
<p>Find me in app/views/author/new.html.erb</p>

ilib/app/views/author/update.html.erb
<h1>Author#update</h1>
<p>Find me in app/views/author/update.html.erb</p>

ilib/app/views/book/edit.html.erb
<%= form_for @book do |f| %>
  <div class="">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </div>

  <div class="">
    <%= f.submit %>
  </div>
<% end %>

ilib/app/views/book/index.html.erb
<% @books.each do |book| %>
        <p>  <%= link_to book.title, book_path(id: book.id) %></p>      <p>  <%= image_tag book.photo_url %></p>
        <p>  <%= book.author%></p>
        <p>  <%= number_to_currency(book.price) %></p>
  <% end %>

ilib/app/views/book/new.html.erb
<%= form_for @book do |f| %>
  <div class="">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </div>

  <div class="">
    <%= f.submit %>
  </div>
<% end %>

ilib/app/views/books/edit.html.erb
<%= form_for @book do |f| %>
  <div class="">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </div>

  <div class="">
    <%= f.submit %>
  </div>
<% end %>

ilib/app/views/books/index.html.erb
<% @books.each do |book| %>
        <p>  <%= link_to book.title, book_path(id: book.id) %></p>      <p>  <%= image_tag book.photo_url %></p>
        <p>  <%= book.author%></p>
        <p>  <%= number_to_currency(book.price) %></p>
  <% end %>

ilib/app/views/books/new.html.erb
<%= form_for @book do |f| %>
  <div class="">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </div>

  <div class="">
    <%= f.submit %>
  </div>
<% end %>

ilib/app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p><%= @book.author%></p>
<p><%=number_to_currency(@book.price)%></p>
<%= image_tag @book.photo_url%>

ilib/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ilib</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class ="container">
  <h1>The Iron Library</h1>
  <%= link_to 'Add A Book', new_book_path %>
  <%= link_to 'View All', root_path %>
</div>
  <div class ="container">
    <%= yield %>
  </div>

</body>
</html>

ilib/app/views/welcome/index.html.erb
<h1>Welcome to the Iron Library</h1>
<p>Hello World</p>